/**
 * FrameInGoa - Community Gallery View
 * Official Hacker Goa House 2026 Member Gallery
 */

const GalleryView = {
  render() {
    const cards = db.getCards() || [];

    return `
      <div class="gallery-container">
        <div class="generator-header text-center">
          <div class="event-pill">
            <span class="pulse-dot"></span> OFFICIAL HACKER GOA HOUSE MEMBER GALLERY
          </div>
          <h2>Hacker Goa House <span class="gradient-text">Member Gallery</span></h2>
          <p>Explore official Builder ID graphics generated by Hacker Goa House participants.</p>
        </div>

        ${cards.length === 0 ? `
          <div class="empty-state-card text-center" style="background: rgba(0, 43, 26, 0.85); border: 2px dashed #FFE600; padding: 50px 20px; border-radius: 20px; margin: 40px 0;">
            <div style="font-size: 60px; margin-bottom: 15px;">🖼️</div>
            <h3 style="color: #FFE600; font-size: 24px; font-weight: 800;">Gallery is Empty</h3>
            <p style="color: #A3D9C3; max-width: 500px; margin: 10px auto 25px auto;">No member cards uploaded yet. Generate your official Builder ID Card and click <strong>"Add My Member Card to Gallery &amp; Leaderboard"</strong> to feature your photo here!</p>
            <button class="btn btn-primary btn-lg" onclick="App.navigateTo('generator')">
              <i class="fas fa-magic"></i> Generate My Builder Card Now 🚀
            </button>
          </div>
        ` : `
          <div class="gallery-grid" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 24px; margin-top: 30px;">
            ${cards.map(card => `
              <div class="gallery-card-item" style="background: rgba(0, 43, 26, 0.9); border: 1px solid #FFE600; border-radius: 16px; overflow: hidden; padding: 12px; box-shadow: 0 8px 24px rgba(0,0,0,0.4);">
                <img src="${card.imageUrl}" alt="${card.userName}" style="width: 100%; border-radius: 10px; display: block;" />
                <div style="padding: 12px 6px 4px 6px; display: flex; justify-content: space-between; align-items: center;">
                  <div>
                    <h4 style="color: #FFFFFF; font-size: 16px; font-weight: 800;">${card.userName}</h4>
                    <span style="color: #FFE600; font-size: 12px; font-weight: 600;">🚩 ${card.teamName || 'Team Builder'}</span>
                  </div>
                  <span style="background: #003622; color: #FF007A; border: 1px solid #FF007A; font-size: 11px; font-weight: 700; padding: 4px 10px; border-radius: 12px;">
                    ${card.builderTitle || 'Code Wizard'}
                  </span>
                </div>
              </div>
            `).join('')}
          </div>
        `}
      </div>
    `;
  }
};
